/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'cpu' in SOPC Builder design 'QSys'
 * SOPC Builder design path: ../../QSys.sopcinfo
 *
 * Generated: Sat Jan 20 11:55:41 PST 2018
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x04009820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1b
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x02000020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x1b
#define ALT_CPU_NAME "cpu"
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x04009000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x04009820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x1b
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x02000020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x1b
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x04009000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_EPCS_FLASH_CONTROLLER
#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_NEW_SDRAM_CONTROLLER
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_AVALON_TIMER
#define __ALTERA_AVALON_UART
#define __ALTERA_NIOS2_GEN2
#define __ALTPLL
#define __FIFOED_AVALON_UART


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone IV E"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart"
#define ALT_STDERR_BASE 0x400a0f8
#define ALT_STDERR_DEV jtag_uart
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/fifoed_avalon_uart_0"
#define ALT_STDIN_BASE 0x400a000
#define ALT_STDIN_DEV fifoed_avalon_uart_0
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "fifoed_avalon_uart"
#define ALT_STDOUT "/dev/jtag_uart"
#define ALT_STDOUT_BASE 0x400a0f8
#define ALT_STDOUT_DEV jtag_uart
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "QSys"


/*
 * altpll_0 configuration
 *
 */

#define ALTPLL_0_BASE 0x400a0e0
#define ALTPLL_0_IRQ -1
#define ALTPLL_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ALTPLL_0_NAME "/dev/altpll_0"
#define ALTPLL_0_SPAN 16
#define ALTPLL_0_TYPE "altpll"
#define ALT_MODULE_CLASS_altpll_0 altpll


/*
 * display_buffer_addr configuration
 *
 */

#define ALT_MODULE_CLASS_display_buffer_addr altera_avalon_pio
#define DISPLAY_BUFFER_ADDR_BASE 0x400a0c0
#define DISPLAY_BUFFER_ADDR_BIT_CLEARING_EDGE_REGISTER 0
#define DISPLAY_BUFFER_ADDR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DISPLAY_BUFFER_ADDR_CAPTURE 0
#define DISPLAY_BUFFER_ADDR_DATA_WIDTH 11
#define DISPLAY_BUFFER_ADDR_DO_TEST_BENCH_WIRING 0
#define DISPLAY_BUFFER_ADDR_DRIVEN_SIM_VALUE 0
#define DISPLAY_BUFFER_ADDR_EDGE_TYPE "NONE"
#define DISPLAY_BUFFER_ADDR_FREQ 50000000
#define DISPLAY_BUFFER_ADDR_HAS_IN 0
#define DISPLAY_BUFFER_ADDR_HAS_OUT 1
#define DISPLAY_BUFFER_ADDR_HAS_TRI 0
#define DISPLAY_BUFFER_ADDR_IRQ -1
#define DISPLAY_BUFFER_ADDR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DISPLAY_BUFFER_ADDR_IRQ_TYPE "NONE"
#define DISPLAY_BUFFER_ADDR_NAME "/dev/display_buffer_addr"
#define DISPLAY_BUFFER_ADDR_RESET_VALUE 0
#define DISPLAY_BUFFER_ADDR_SPAN 16
#define DISPLAY_BUFFER_ADDR_TYPE "altera_avalon_pio"


/*
 * display_buffer_ctrl configuration
 *
 */

#define ALT_MODULE_CLASS_display_buffer_ctrl altera_avalon_pio
#define DISPLAY_BUFFER_CTRL_BASE 0x400a0a0
#define DISPLAY_BUFFER_CTRL_BIT_CLEARING_EDGE_REGISTER 0
#define DISPLAY_BUFFER_CTRL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DISPLAY_BUFFER_CTRL_CAPTURE 0
#define DISPLAY_BUFFER_CTRL_DATA_WIDTH 8
#define DISPLAY_BUFFER_CTRL_DO_TEST_BENCH_WIRING 0
#define DISPLAY_BUFFER_CTRL_DRIVEN_SIM_VALUE 0
#define DISPLAY_BUFFER_CTRL_EDGE_TYPE "NONE"
#define DISPLAY_BUFFER_CTRL_FREQ 50000000
#define DISPLAY_BUFFER_CTRL_HAS_IN 0
#define DISPLAY_BUFFER_CTRL_HAS_OUT 1
#define DISPLAY_BUFFER_CTRL_HAS_TRI 0
#define DISPLAY_BUFFER_CTRL_IRQ -1
#define DISPLAY_BUFFER_CTRL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DISPLAY_BUFFER_CTRL_IRQ_TYPE "NONE"
#define DISPLAY_BUFFER_CTRL_NAME "/dev/display_buffer_ctrl"
#define DISPLAY_BUFFER_CTRL_RESET_VALUE 0
#define DISPLAY_BUFFER_CTRL_SPAN 16
#define DISPLAY_BUFFER_CTRL_TYPE "altera_avalon_pio"


/*
 * display_buffer_data configuration
 *
 */

#define ALT_MODULE_CLASS_display_buffer_data altera_avalon_pio
#define DISPLAY_BUFFER_DATA_BASE 0x400a0b0
#define DISPLAY_BUFFER_DATA_BIT_CLEARING_EDGE_REGISTER 0
#define DISPLAY_BUFFER_DATA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DISPLAY_BUFFER_DATA_CAPTURE 0
#define DISPLAY_BUFFER_DATA_DATA_WIDTH 32
#define DISPLAY_BUFFER_DATA_DO_TEST_BENCH_WIRING 0
#define DISPLAY_BUFFER_DATA_DRIVEN_SIM_VALUE 0
#define DISPLAY_BUFFER_DATA_EDGE_TYPE "NONE"
#define DISPLAY_BUFFER_DATA_FREQ 50000000
#define DISPLAY_BUFFER_DATA_HAS_IN 0
#define DISPLAY_BUFFER_DATA_HAS_OUT 1
#define DISPLAY_BUFFER_DATA_HAS_TRI 0
#define DISPLAY_BUFFER_DATA_IRQ -1
#define DISPLAY_BUFFER_DATA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DISPLAY_BUFFER_DATA_IRQ_TYPE "NONE"
#define DISPLAY_BUFFER_DATA_NAME "/dev/display_buffer_data"
#define DISPLAY_BUFFER_DATA_RESET_VALUE 0
#define DISPLAY_BUFFER_DATA_SPAN 16
#define DISPLAY_BUFFER_DATA_TYPE "altera_avalon_pio"


/*
 * epcs_flash_controller configuration
 *
 */

#define ALT_MODULE_CLASS_epcs_flash_controller altera_avalon_epcs_flash_controller
#define EPCS_FLASH_CONTROLLER_BASE 0x4009000
#define EPCS_FLASH_CONTROLLER_IRQ 2
#define EPCS_FLASH_CONTROLLER_IRQ_INTERRUPT_CONTROLLER_ID 0
#define EPCS_FLASH_CONTROLLER_NAME "/dev/epcs_flash_controller"
#define EPCS_FLASH_CONTROLLER_REGISTER_OFFSET 1024
#define EPCS_FLASH_CONTROLLER_SPAN 2048
#define EPCS_FLASH_CONTROLLER_TYPE "altera_avalon_epcs_flash_controller"


/*
 * fifoed_avalon_uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_fifoed_avalon_uart_0 fifoed_avalon_uart
#define FIFOED_AVALON_UART_0_ADD_ERROR_BITS 0
#define FIFOED_AVALON_UART_0_BASE 0x400a000
#define FIFOED_AVALON_UART_0_BAUD 115200
#define FIFOED_AVALON_UART_0_DATA_BITS 8
#define FIFOED_AVALON_UART_0_FIFO_EXPORT_USED 0
#define FIFOED_AVALON_UART_0_FIXED_BAUD 1
#define FIFOED_AVALON_UART_0_FREQ 50000000
#define FIFOED_AVALON_UART_0_GAP_VALUE 4
#define FIFOED_AVALON_UART_0_IRQ 5
#define FIFOED_AVALON_UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define FIFOED_AVALON_UART_0_NAME "/dev/fifoed_avalon_uart_0"
#define FIFOED_AVALON_UART_0_PARITY 'N'
#define FIFOED_AVALON_UART_0_PASS_ERROR_BITS 0
#define FIFOED_AVALON_UART_0_RX_FIFO_LE 0
#define FIFOED_AVALON_UART_0_RX_FIFO_SIZE 1024
#define FIFOED_AVALON_UART_0_RX_IRQ_THRESHOLD 1
#define FIFOED_AVALON_UART_0_SIM_CHAR_STREAM ""
#define FIFOED_AVALON_UART_0_SIM_TRUE_BAUD 0
#define FIFOED_AVALON_UART_0_SPAN 64
#define FIFOED_AVALON_UART_0_STOP_BITS 1
#define FIFOED_AVALON_UART_0_SYNC_REG_DEPTH 2
#define FIFOED_AVALON_UART_0_TIMEOUT_VALUE 4
#define FIFOED_AVALON_UART_0_TIMESTAMP_WIDTH 8
#define FIFOED_AVALON_UART_0_TRANSMIT_PIN 0
#define FIFOED_AVALON_UART_0_TX_FIFO_LE 0
#define FIFOED_AVALON_UART_0_TX_FIFO_SIZE 8
#define FIFOED_AVALON_UART_0_TX_IRQ_THRESHOLD 4
#define FIFOED_AVALON_UART_0_TYPE "fifoed_avalon_uart"
#define FIFOED_AVALON_UART_0_UHW_CTS 0
#define FIFOED_AVALON_UART_0_USE_CTS_RTS 0
#define FIFOED_AVALON_UART_0_USE_EOP_REGISTER 0
#define FIFOED_AVALON_UART_0_USE_EXT_TIMESTAMP 0
#define FIFOED_AVALON_UART_0_USE_GAP_DETECTION 1
#define FIFOED_AVALON_UART_0_USE_RX_FIFO 1
#define FIFOED_AVALON_UART_0_USE_RX_TIMEOUT 0
#define FIFOED_AVALON_UART_0_USE_STATUS_BIT_CLEAR 0
#define FIFOED_AVALON_UART_0_USE_TIMESTAMP 0
#define FIFOED_AVALON_UART_0_USE_TX_FIFO 1


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK SYS_CLK_TIMER
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart altera_avalon_jtag_uart
#define JTAG_UART_BASE 0x400a0f8
#define JTAG_UART_IRQ 0
#define JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NAME "/dev/jtag_uart"
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_SPAN 8
#define JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


/*
 * onchip_memory2 configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory2 altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_BASE 0x4000000
#define ONCHIP_MEMORY2_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_DUAL_PORT 0
#define ONCHIP_MEMORY2_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_INIT_CONTENTS_FILE "QSys_onchip_memory2"
#define ONCHIP_MEMORY2_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY2_IRQ -1
#define ONCHIP_MEMORY2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY2_NAME "/dev/onchip_memory2"
#define ONCHIP_MEMORY2_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY2_SINGLE_CLOCK_OP 1
#define ONCHIP_MEMORY2_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_SIZE_VALUE 26000
#define ONCHIP_MEMORY2_SPAN 26000
#define ONCHIP_MEMORY2_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY2_WRITABLE 1


/*
 * pio_led configuration
 *
 */

#define ALT_MODULE_CLASS_pio_led altera_avalon_pio
#define PIO_LED_BASE 0x400a0d0
#define PIO_LED_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_LED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_LED_CAPTURE 0
#define PIO_LED_DATA_WIDTH 8
#define PIO_LED_DO_TEST_BENCH_WIRING 0
#define PIO_LED_DRIVEN_SIM_VALUE 0
#define PIO_LED_EDGE_TYPE "NONE"
#define PIO_LED_FREQ 50000000
#define PIO_LED_HAS_IN 0
#define PIO_LED_HAS_OUT 1
#define PIO_LED_HAS_TRI 0
#define PIO_LED_IRQ -1
#define PIO_LED_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_LED_IRQ_TYPE "NONE"
#define PIO_LED_NAME "/dev/pio_led"
#define PIO_LED_RESET_VALUE 0
#define PIO_LED_SPAN 16
#define PIO_LED_TYPE "altera_avalon_pio"


/*
 * sdram_controller configuration
 *
 */

#define ALT_MODULE_CLASS_sdram_controller altera_avalon_new_sdram_controller
#define SDRAM_CONTROLLER_BASE 0x2000000
#define SDRAM_CONTROLLER_CAS_LATENCY 2
#define SDRAM_CONTROLLER_CONTENTS_INFO
#define SDRAM_CONTROLLER_INIT_NOP_DELAY 0.0
#define SDRAM_CONTROLLER_INIT_REFRESH_COMMANDS 8
#define SDRAM_CONTROLLER_IRQ -1
#define SDRAM_CONTROLLER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_CONTROLLER_IS_INITIALIZED 1
#define SDRAM_CONTROLLER_NAME "/dev/sdram_controller"
#define SDRAM_CONTROLLER_POWERUP_DELAY 200.0
#define SDRAM_CONTROLLER_REFRESH_PERIOD 0.75
#define SDRAM_CONTROLLER_REGISTER_DATA_IN 1
#define SDRAM_CONTROLLER_SDRAM_ADDR_WIDTH 0x18
#define SDRAM_CONTROLLER_SDRAM_BANK_WIDTH 2
#define SDRAM_CONTROLLER_SDRAM_COL_WIDTH 9
#define SDRAM_CONTROLLER_SDRAM_DATA_WIDTH 16
#define SDRAM_CONTROLLER_SDRAM_NUM_BANKS 4
#define SDRAM_CONTROLLER_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_CONTROLLER_SDRAM_ROW_WIDTH 13
#define SDRAM_CONTROLLER_SHARED_DATA 0
#define SDRAM_CONTROLLER_SIM_MODEL_BASE 0
#define SDRAM_CONTROLLER_SPAN 33554432
#define SDRAM_CONTROLLER_STARVATION_INDICATOR 0
#define SDRAM_CONTROLLER_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_CONTROLLER_TYPE "altera_avalon_new_sdram_controller"
#define SDRAM_CONTROLLER_T_AC 6.5
#define SDRAM_CONTROLLER_T_MRD 3
#define SDRAM_CONTROLLER_T_RCD 20.0
#define SDRAM_CONTROLLER_T_RFC 70.0
#define SDRAM_CONTROLLER_T_RP 20.0
#define SDRAM_CONTROLLER_T_WR 14.0


/*
 * sys_clk_timer configuration
 *
 */

#define ALT_MODULE_CLASS_sys_clk_timer altera_avalon_timer
#define SYS_CLK_TIMER_ALWAYS_RUN 0
#define SYS_CLK_TIMER_BASE 0x400a080
#define SYS_CLK_TIMER_COUNTER_SIZE 32
#define SYS_CLK_TIMER_FIXED_PERIOD 0
#define SYS_CLK_TIMER_FREQ 50000000
#define SYS_CLK_TIMER_IRQ 1
#define SYS_CLK_TIMER_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SYS_CLK_TIMER_LOAD_VALUE 49999
#define SYS_CLK_TIMER_MULT 0.001
#define SYS_CLK_TIMER_NAME "/dev/sys_clk_timer"
#define SYS_CLK_TIMER_PERIOD 1
#define SYS_CLK_TIMER_PERIOD_UNITS "ms"
#define SYS_CLK_TIMER_RESET_OUTPUT 0
#define SYS_CLK_TIMER_SNAPSHOT 1
#define SYS_CLK_TIMER_SPAN 32
#define SYS_CLK_TIMER_TICKS_PER_SEC 1000
#define SYS_CLK_TIMER_TIMEOUT_PULSE_OUTPUT 0
#define SYS_CLK_TIMER_TYPE "altera_avalon_timer"


/*
 * sysid configuration
 *
 */

#define ALT_MODULE_CLASS_sysid altera_avalon_sysid_qsys
#define SYSID_BASE 0x400a0f0
#define SYSID_ID 0
#define SYSID_IRQ -1
#define SYSID_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_NAME "/dev/sysid"
#define SYSID_SPAN 8
#define SYSID_TIMESTAMP 1516477923
#define SYSID_TYPE "altera_avalon_sysid_qsys"


/*
 * timer_0 configuration
 *
 */

#define ALT_MODULE_CLASS_timer_0 altera_avalon_timer
#define TIMER_0_ALWAYS_RUN 0
#define TIMER_0_BASE 0x400a060
#define TIMER_0_COUNTER_SIZE 32
#define TIMER_0_FIXED_PERIOD 0
#define TIMER_0_FREQ 50000000
#define TIMER_0_IRQ 3
#define TIMER_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_0_LOAD_VALUE 49999
#define TIMER_0_MULT 0.001
#define TIMER_0_NAME "/dev/timer_0"
#define TIMER_0_PERIOD 1
#define TIMER_0_PERIOD_UNITS "ms"
#define TIMER_0_RESET_OUTPUT 0
#define TIMER_0_SNAPSHOT 1
#define TIMER_0_SPAN 32
#define TIMER_0_TICKS_PER_SEC 1000
#define TIMER_0_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_0_TYPE "altera_avalon_timer"


/*
 * uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_uart_0 altera_avalon_uart
#define UART_0_BASE 0x400a040
#define UART_0_BAUD 115200
#define UART_0_DATA_BITS 8
#define UART_0_FIXED_BAUD 0
#define UART_0_FREQ 50000000
#define UART_0_IRQ 4
#define UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define UART_0_NAME "/dev/uart_0"
#define UART_0_PARITY 'N'
#define UART_0_SIM_CHAR_STREAM ""
#define UART_0_SIM_TRUE_BAUD 0
#define UART_0_SPAN 32
#define UART_0_STOP_BITS 1
#define UART_0_SYNC_REG_DEPTH 2
#define UART_0_TYPE "altera_avalon_uart"
#define UART_0_USE_CTS_RTS 0
#define UART_0_USE_EOP_REGISTER 0

#endif /* __SYSTEM_H_ */
